apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: kwola-__KWOLA_ENV__-testingworker
  name: kwola-__KWOLA_ENV__-testingworker-hpa
spec:
  maxReplicas: 100
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: kwola-__KWOLA_ENV__-testingworker
  targetCPUUtilizationPercentage: 90

