apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kwola-__KWOLA_ENV__-testingworker
  name: kwola-__KWOLA_ENV__-testingworker
  namespace: default
spec:
  selector:
    matchLabels:
      app: kwola-__KWOLA_ENV__-testingworker
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kwola-__KWOLA_ENV__-testingworker
    spec:
      containers:
      - image: gcr.io/kwola-cloud/kwola:__REVISION_ID__-__KWOLA_ENV__-testingworker
        imagePullPolicy: IfNotPresent
        name: kwola-cloud-sha256
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 15
      nodeSelector:
        cloud.google.com/gke-preemptible: "true"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
