apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kwola-__KWOLA_ENV__-api
  name: kwola-__KWOLA_ENV__-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: kwola-__KWOLA_ENV__-api
  strategy:
    rollingUpdate:
      maxSurge: __MAX_SURGE__
      maxUnavailable: __MAX_UNAVAILABLE__
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kwola-__KWOLA_ENV__-api
    spec:
      containers:
      - env:
        - name: KWOLA_ENV
          value: __KWOLA_ENV__
        image: gcr.io/kwola-cloud/kwola-api-__KWOLA_ENV__:__REVISION_ID__
        imagePullPolicy: IfNotPresent
        name: kwola-cloud-sha256
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /api/home
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "3"
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      priorityClassName: __KWOLA_ENV__-priority
      terminationGracePeriodSeconds: 15
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
