apiVersion: v1
kind: Service
metadata:
  name: kwola-__KWOLA_ENV__-api
  labels:
    app: kwola-__KWOLA_ENV__-api
  name: kwola-__KWOLA_ENV__-api
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kwola-__KWOLA_ENV__-api
  sessionAffinity: None
  type: ClusterIP
