steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: Build API Server Docker Image
  args:
    - "--destination=gcr.io/kwola-cloud/kwola-api-$_KWOLA_ENV:$REVISION_ID"
    - "--destination=gcr.io/kwola-cloud/kwola-api-$_KWOLA_ENV:latest"
    - "--cache=true"
    - "--cache-ttl=720h"
    - "--snapshotMode=time"
    - "--build-arg"
    - "KWOLA_ENV=$_KWOLA_ENV"
    - "--build-arg"
    - "REVISION_ID=$REVISION_ID"
    - "-f"
    - "deployment/api/Dockerfile"
  timeout: 1200s
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'cluster-info'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kwolacloudmain'
  timeout: 30s
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update Deployment on Kubernetes
  entrypoint: /bin/bash
  args:
  - "./deployment/api/update_api_server.sh"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kwolacloudmain'
  - 'KWOLA_ENV=$_KWOLA_ENV'
  - 'REVISION_ID=$REVISION_ID'
  timeout: 600s
- name: 'gcr.io/cloud-builders/gcloud'
  id: Run Migration Job
  entrypoint: /bin/bash
  args:
  - "./deployment/api/run_migration_job.sh"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kwolacloudmain'
  - 'KWOLA_ENV=$_KWOLA_ENV'
  - 'REVISION_ID=$REVISION_ID'
  timeout: 600s
timeout: 15000s