apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kwola-db-reset-__KWOLA_ENV__
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kwola-cloud-sha256
            image: gcr.io/kwola-cloud/kwola-api-__KWOLA_ENV__:__REVISION_ID__
            imagePullPolicy: Always
            command: [ "kwolacloud_load_demo_db" ]
            resources:
              requests:
                cpu: 1000m
                memory: 1024Mi
          restartPolicy: OnFailure
          priorityClassName: __KWOLA_ENV__-priority
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 15
      backoffLimit: 4



