apiVersion: batch/v1
kind: Job
metadata:
  name: kwola-migration-__KWOLA_ENV__
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
      - name: kwola-cloud-sha256
        image: gcr.io/kwola-cloud/kwola:__REVISION_ID__-__KWOLA_ENV__-api
        command: ["appraisal_run_migrations",  "__KWOLA_ENV__.ini"]
        resources:
          requests:
            cpu: 1
            memory: 512Mi
      restartPolicy: Never
      priorityClassName: __KWOLA_ENV__-priority
  backoffLimit: 4
