apiVersion: batch/v1
kind: Job
metadata:
  name: kwola-migration-__KWOLA_ENV__
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
      - name: kwola-cloud-sha256
        image: gcr.io/kwola-cloud/kwola-api-__KWOLA_ENV__:__REVISION_ID__
        command: ["kwolacloud_run_migrations"]
        resources:
          requests:
            cpu: 1
            memory: 3Gi
        env:
            - name: KWOLA_ENV
              value: __KWOLA_ENV__
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
      restartPolicy: OnFailure
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      priorityClassName: __KWOLA_ENV__-background-priority

  backoffLimit: 4

