apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: demobackup-priority
value: 10000
globalDefault: false
description: "This is the priority class for demo backup pods. Demo backup is the db that is restored to the demo environment every day. There should be no live pods running for this environment."
