apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: kwola-__KWOLA_ENV__-trainingworker
  name: kwola-__KWOLA_ENV__-trainingworker-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: kwola-KWOLA_ENV-trainingworker
  targetCPUUtilizationPercentage: 80

