steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: Build Frontend Docker Image
  args:
    - "--destination=gcr.io/kwola-cloud/kwola:$REVISION_ID-$_KWOLA_ENV-frontend"
    - "--cache=true"
    - "--cache-ttl=720h"
    - "--snapshotMode=time"
    - "--build-arg"
    - "KWOLA_ENV=$_KWOLA_ENV"
    - "-f"
    - "deployment/frontend/Dockerfile"
  timeout: 1800s
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'cluster-info'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kwolacloudmain'
  timeout: 30s
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update Frontend Server Deployment
  entrypoint: /bin/bash
  args:
  - "./deployment/frontend/update_frontend_server.sh"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kwolacloudmain'
  - 'KWOLA_ENV=$_KWOLA_ENV'
  - 'REVISION_ID=$REVISION_ID'
  timeout: 600s
timeout: 3600s
options:
  machineType: n1-highcpu-8