steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build Frontend Docker Image
  args:
    - "build"
    - "."
    - "-t"
    - "gcr.io/kwola-cloud/kwola:$REVISION_ID-$_KWOLA_ENV-frontend"
    - "--build-arg"
    - "KWOLA_ENV=$_KWOLA_ENV"
    - "-f"
    - "deployment/frontend/Dockerfile"
  timeout: 1800s
- name: 'gcr.io/cloud-builders/docker'
  id: Push the API Server
  args:
    - "push"
    - "gcr.io/kwola-cloud/kwola:$REVISION_ID-$_KWOLA_ENV-frontend"
  timeout: 1800s
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'cluster-info'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kwolacloudmain'
  timeout: 30s
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update Frontend Server Deployment
  entrypoint: /bin/bash
  args:
  - "./deployment/frontend/update_frontend_server.sh"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kwolacloudmain'
  - 'KWOLA_ENV=$_KWOLA_ENV'
  - 'REVISION_ID=$REVISION_ID'
  timeout: 600s
timeout: 3600s
