apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: kwola-__KWOLA_ENV__-frontend
  name: kwola-__KWOLA_ENV__-frontend-hpa
spec:
  maxReplicas: __MAXIMUM_REPLICATIONS__
  minReplicas: MINIMUM_REPLICATIONS
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: kwola-__KWOLA_ENV__-frontend
  targetCPUUtilizationPercentage: 80

