apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kwola-__KWOLA_ENV__-frontend
  name: kwola-__KWOLA_ENV__-frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: kwola-__KWOLA_ENV__-frontend
  strategy:
    rollingUpdate:
      maxSurge: __MAX_SURGE__
      maxUnavailable: __MAX_UNAVAILABLE__
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kwola-__KWOLA_ENV__-frontend
    spec:
      containers:
      - image: gcr.io/kwola-cloud/kwola-frontend-__KWOLA_ENV__:__REVISION_ID__
        imagePullPolicy: Always
        name: kwola-cloud-sha256
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      priorityClassName: __KWOLA_ENV__-priority
      terminationGracePeriodSeconds: 15
