apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kwola-__KWOLA_ENV__-frontend
  name: kwola-__KWOLA_ENV__-frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: kwola-__KWOLA_ENV__-frontend
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kwola-__KWOLA_ENV__-frontend
    spec:
      containers:
      - image: gcr.io/kwola-cloud/kwola:__REVISION_ID__-__KWOLA_ENV__-frontend
        imagePullPolicy: IfNotPresent
        name: kwola-cloud-sha256
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 15
      nodeSelector:
        cloud.google.com/gke-preemptible: "true"
