steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: Build worker image
  args: [
    "--destination=gcr.io/kwola-cloud/kwola-worker-$_KWOLA_ENV:$REVISION_ID",
    "--destination=gcr.io/kwola-cloud/kwola-worker-$_KWOLA_ENV:latest",
    "--cache=false",
    "--cache-ttl=720h",
    "--snapshotMode=time",
    "--build-arg",
    "KWOLA_ENV=$_KWOLA_ENV",
    "--build-arg",
    "REVISION_ID=$REVISION_ID",
    "-f",
    "deployment/worker/Dockerfile"
  ]
  timeout: 1200s
- name: 'gcr.io/cloud-builders/kubectl'
  id: Fetch Kubernetes Auth
  args:
  - 'cluster-info'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kwolacloudmain-4'
  timeout: 30s

timeout: 15000s
options:
  machineType: 'UNSPECIFIED'
