steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: Build worker image
  args: [
    "--destination=gcr.io/kwola-cloud/kwola:$REVISION_ID-$_KWOLA_ENV-worker",
    "--cache=true",
    "--cache-ttl=720h",
    "--snapshotMode=time",
    "--build-arg",
    "KWOLA_ENV=$_KWOLA_ENV",
    "-f",
    "deployment/worker/Dockerfile"
  ]
  timeout: 7200s
- name: 'gcr.io/cloud-builders/kubectl'
  id: Fetch Kubernetes Auth
  args:
  - 'cluster-info'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kwolacloudmain'
  timeout: 30s
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update Training Server Cron Job
  entrypoint: /bin/bash
  args:
  - "./deployment/worker/update_worker.sh"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kwolacloudmain'
  - 'KWOLA_ENV=$_KWOLA_ENV'
  - 'REVISION_ID=$REVISION_ID'
  timeout: 1200s

timeout: 15000s
options:
  machineType: 'n1-highcpu-8'