apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: kwola-__KWOLA_ENV__-worker
  name: kwola-__KWOLA_ENV__-worker-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: kwola-KWOLA_ENV-worker
  targetCPUUtilizationPercentage: 80

