apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kwola-__KWOLA_ENV__-worker
  name: kwola-__KWOLA_ENV__-worker
  namespace: default
spec:
  selector:
    matchLabels:
      app: kwola-__KWOLA_ENV__-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kwola-__KWOLA_ENV__-worker
    spec:
      containers:
      - image: gcr.io/kwola-cloud/kwola:__REVISION_ID__-__KWOLA_ENV__-worker
        imagePullPolicy: IfNotPresent
        name: kwola-cloud-sha256
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            cpu: 500m
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 15
      nodeSelector:
        cloud.google.com/gke-preemptible: "true"
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory